name: build and upload
on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build_and_upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest] # 

    steps:
    - uses: mamba-org/setup-micromamba@v1
    - uses: actions/checkout@v4
    - name: install PowerDiagram
      run: git clone https://github.com/PowerDiagram/PowerDiagram.git modules/PowerDiagram
    - name: install pybind11
      run: git clone https://github.com/pybind/pybind11.git modules/pybind11
    - name: install eigen3
      run: git clone https://gitlab.com/libeigen/eigen.git modules/eigen3
    - name: build the wheels
      run: make -C src/python build_all
    - name: install pip packages
      run: pip install twine
    - name: upload the packages
      run: python -m twine upload --skip-existing -u ${{ secrets.PIPY_USERNAME }} -p ${{ secrets.PIPY_PASSWORD }} --repository pypi --verbose src/python/dist/*
