name: build and upload
on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build_and_upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest] # 

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: mamba-org/setup-micromamba@v1
    - name: build the wheels
      run: make -C src/python build_all
    - name: install twine
      run: pip install twine
    - name: upload the packages
      run: python -m twine upload --skip-existing -u ${{ secrets.PIPY_USERNAME }} -p ${{ secrets.PIPY_PASSWORD }} --repository pypi --verbose src/python/dist/*
